// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("newsigv4")
	ScopeName = "github.com/aws-observability/aws-otel-collector/extensions/newsigv4"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
